=== akotvojamama/Projekt---zna-kovac-jazyky/XMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="profily_programu_zbrush">
    <xs:complexType>
      <xs:sequence>
        <!--Jednotlivé profily-->
        <xs:element name="profil" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <!--Základní charakteristika-->
              <xs:element name="zakladni">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="language" name="jazyk"/>
                    <xs:element type="xs:string" name="jmeno_profilu"/>
                    <xs:element name="menu">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="menu_funkci">
                            <xs:attribute type="xs:string" name="vlastnost" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="tvurce">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="pohlavi" use="optional"/>
                            <xs:attribute type="xs:string" name="vek" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ukladani_projektu">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute type="xs:string" name="ulozeni" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="vytvoreni_profilu">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:date" name="datum"/>
                          <xs:element type="xs:time" name="cas"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!--Nastavení modelu profilu-->
              <xs:element name="nastaveni_modelu">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="tvar">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="tvar_objektu" name="vychozi_tvar"/>
                          <xs:element name="polygonalni_rozliseni">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="poly_rozliseni">
                                  <xs:attribute type="xs:int" name="polygony" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="poly_tvar" name="tvar_polygonu"/>
                          <xs:element type="xs:string" name="velikost_modelu"/>
                          <xs:element type="xs:string" name="umisteni"/>
                          <xs:element type="xs:string" name="rotace"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="osy">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="umisteni"/>
                          <xs:element type="xs:string" name="rotace"/>
                          <xs:element type="xs:boolean" name="viditelnost"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="textura">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="color" name="barva"/>
                          <xs:element type="procenta" name="odrazivost"/>
                          <xs:element type="procenta" name="hrbolatost"/>
                          <xs:element type="procenta" name="jas"/>
                          <xs:element type="procenta" name="sum"/>
                          <xs:element type="procenta" name="alpha"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!--Nastavení scény profilu-->
              <xs:element name="scena">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="pozadi">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="typ_pozadi">
                            <xs:attribute type="xs:string" name="typ" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="soubor" name="slunce"/>
                    <xs:element type="soubor" name="obloha"/>
                    <xs:element type="stiny" name="stin"/>
                    <xs:element type="mracky" name="mraky"/>
                    <xs:element type="soubor" name="podlaha"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!--Nastavení renderu profilu-->
              <xs:element name="render">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="render_system" name="rendrovaci_system"/>
                    <xs:element name="vystup">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:integer" name="sirka"/>
                          <xs:element type="xs:integer" name="vyska"/>
                          <xs:element type="xs:string" name="rozliseni"/>
                          <xs:element name="soubor">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:string" name="typ" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="vyhlazovani">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="vyhladit" name="vyhlazeni"/>
                          <xs:element type="filtrik" name="filtr"/>
                          <xs:element type="xs:boolean" name="vlastni_velikost"/>
                          <xs:element name="mira_mip">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="mira">
                                  <xs:attribute type="xs:string" name="mip" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="fragmenty" name="male_fragmenty"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="globalni_iluminace">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="iluminate" name="primarni_metoda"/>
                          <xs:element type="iluminate" name="sekundarni_metoda"/>
                          <xs:element name="mnozstvi_odrazu">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="mira">
                                  <xs:attribute type="xs:integer" name="pocet_odrazu" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:integer" name="gammut"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="ambient_occlusion">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="color" name="barva"/>
                          <xs:element type="procenta" name="rozptyl"/>
                          <xs:element type="procenta" name="presnost"/>
                          <xs:element type="procenta" name="kontrast"/>
                          <xs:element type="xs:boolean" name="pouzit"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Definice omezení -->
  <xs:simpleType name="language">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Čeština" />
         <xs:enumeration value="Angličtina" />
         <xs:enumeration value="Němčina" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="menu_funkci">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Základní" />
         <xs:enumeration value="Rozšířené" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="tvar_objektu">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Human" />
         <xs:enumeration value="Rectangle" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="poly_rozliseni">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Vysoké" />
         <xs:enumeration value="Střední" />
         <xs:enumeration value="Nízké" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="poly_tvar">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Čtverce" />
         <xs:enumeration value="Trojúhelníky" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="color">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Červená" />
         <xs:enumeration value="Modrá" />
         <xs:enumeration value="Zelená" />
         <xs:enumeration value="Šedá" />
         <xs:enumeration value="Černá" />
         <xs:enumeration value="Hnědá" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="procenta">
      <xs:restriction base="xs:integer">
         <xs:minInclusive value="0" />
         <xs:maxInclusive value="100" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="typ_pozadi">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Obloha" />
         <xs:enumeration value="Barva" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="soubor">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Přednastavené" />
         <xs:enumeration value="Jiné" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="stiny">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Ostrý" />
         <xs:enumeration value="Měkký" />
         <xs:enumeration value="Oblast" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="mracky">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Volumetrické" />
         <xs:enumeration value="Jiné" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="render_system">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Standardní" />
         <xs:enumeration value="Fyzikální" />
         <xs:enumeration value="Jiný" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="vyhladit">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Geometrie" />
         <xs:enumeration value="Vlastní" />
      </xs:restriction>
  </xs:simpleType>
    <xs:simpleType name="filtrik">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Kubický" />
         <xs:enumeration value="Sférický" />
         <xs:enumeration value="UV" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="mira">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Vysoká" />
         <xs:enumeration value="Střední" />
         <xs:enumeration value="Nízká" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="fragmenty">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Hybridní" />
         <xs:enumeration value="Standardní" />
      </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="iluminate">
      <xs:restriction base="xs:string">
         <xs:enumeration value="Irradiance Cache" />
         <xs:enumeration value="QMC" />
      </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== akotvojamama/Projekt---zna-kovac-jazyky/XMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<?xml-stylesheet type="text/xsl" href="transformace.xsl"?>
<profily_programu_zbrush xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchema.xsd">
         
    <!--profil 1-->
    <profil id="1">
        <zakladni>
            <jazyk>Čeština</jazyk>
            <jmeno_profilu>Charaktery</jmeno_profilu>
            <menu vlastnost="Soubor extra funkcí">Rozšířené</menu>
            <tvurce pohlavi="muž" vek= "63 let">Petr Skočdopole</tvurce>
            <ukladani_projektu ulozeni="C:\Zbrush\characters">Složka charekterů Zbrush</ukladani_projektu>
            <vytvoreni_profilu>
                <datum>2015-11-05</datum>
                <cas>11:22:55</cas>
            </vytvoreni_profilu>
        </zakladni>
        <nastaveni_modelu>
            <tvar>
                <vychozi_tvar>Human</vychozi_tvar>
                <polygonalni_rozliseni polygony="50000">Vysoké</polygonalni_rozliseni>
                <tvar_polygonu>Čtverce</tvar_polygonu>
                <velikost_modelu>50x40x30</velikost_modelu>
                <umisteni>0,0,0</umisteni>
                <rotace>0,0,0</rotace>
            </tvar>
            <osy>
                <umisteni>20,20,20</umisteni>
                <rotace>0,0,0</rotace>
                <viditelnost>false</viditelnost>
            </osy>
            <textura>
                <barva>Červená</barva>
                <odrazivost>20</odrazivost>
                <hrbolatost>0</hrbolatost>
                <jas>10</jas>
                <sum>30</sum>
                <alpha>35</alpha>
            </textura>
        </nastaveni_modelu>
        <scena>
            <pozadi typ=".jpg">Obloha</pozadi>
            <slunce>Přednastavené</slunce>
            <obloha>Přednastavené</obloha>
            <stin>Ostrý</stin>
            <mraky>Volumetrické</mraky>
            <podlaha>Přednastavené</podlaha>  
        </scena>
        <render>
            <rendrovaci_system>Standardní</rendrovaci_system>
            <vystup>
                <sirka>1280</sirka>
                <vyska>720</vyska>
                <rozliseni>72 pixelů</rozliseni>
                <soubor typ=".png">render</soubor>
            </vystup>
            <vyhlazovani>
                <vyhlazeni>Geometrie</vyhlazeni>
                <filtr>Kubický</filtr>
                <vlastni_velikost>true</vlastni_velikost>
                <mira_mip mip="50">Vysoká</mira_mip>
                <male_fragmenty>Hybridní</male_fragmenty>
            </vyhlazovani>
            <globalni_iluminace>
                <primarni_metoda>Irradiance Cache</primarni_metoda>
                <sekundarni_metoda>QMC</sekundarni_metoda>
                <mnozstvi_odrazu pocet_odrazu="5">Vysoká</mnozstvi_odrazu>
                <gammut>1</gammut>
            </globalni_iluminace>
            <ambient_occlusion>
                <barva>Černá</barva>
                <rozptyl>90</rozptyl>
                <presnost>50</presnost>
                <kontrast>0</kontrast>
                <pouzit>true</pouzit>
            </ambient_occlusion>
        </render>
    </profil>
         
    <!--profil 2-->
    <profil id="2">
        <zakladni>
            <jazyk>Čeština</jazyk>
            <jmeno_profilu>Stavby</jmeno_profilu>
            <menu vlastnost="Soubor extra funkcí">Rozšířené</menu>
            <tvurce pohlavi="muž" vek= "42 let">Jan Novák</tvurce>
            <ukladani_projektu ulozeni="C:\Zbrush\buildings">Složka budov Zbrush</ukladani_projektu>
            <vytvoreni_profilu>
                <datum>2016-12-11</datum>
                <cas>14:26:41</cas>
            </vytvoreni_profilu>
        </zakladni>
        <nastaveni_modelu>
            <tvar>
                <vychozi_tvar>Rectangle</vychozi_tvar>
                <polygonalni_rozliseni polygony="2000">Nízké</polygonalni_rozliseni>
                <tvar_polygonu>Čtverce</tvar_polygonu>
                <velikost_modelu>50x40x30</velikost_modelu>
                <umisteni>0,0,0</umisteni>
                <rotace>0,0,0</rotace>
            </tvar>
            <osy>
                <umisteni>20,40,20</umisteni>
                <rotace>0,0,0</rotace>
                <viditelnost>true</viditelnost>
            </osy>
            <textura>
                <barva>Modrá</barva>
                <odrazivost>10</odrazivost>
                <hrbolatost>50</hrbolatost>
                <jas>10</jas>
                <sum>30</sum>
                <alpha>35</alpha>
            </textura>
        </nastaveni_modelu>
        <scena>
            <pozadi typ=".jpg">Obloha</pozadi>
            <slunce>Přednastavené</slunce>
            <obloha>Přednastavené</obloha>
            <stin>Ostrý</stin>
            <mraky>Volumetrické</mraky>
            <podlaha>Přednastavené</podlaha>  
        </scena>
        <render>
            <rendrovaci_system>Fyzikální</rendrovaci_system>
            <vystup>
                <sirka>1280</sirka>
                <vyska>720</vyska>
                <rozliseni>72 pixelů</rozliseni>
                <soubor typ=".png">render</soubor>
            </vystup>
            <vyhlazovani>
                <vyhlazeni>Geometrie</vyhlazeni>
                <filtr>Kubický</filtr>
                <vlastni_velikost>true</vlastni_velikost>
                <mira_mip mip="50">Vysoká</mira_mip>
                <male_fragmenty>Hybridní</male_fragmenty>
            </vyhlazovani>
            <globalni_iluminace>
                <primarni_metoda>Irradiance Cache</primarni_metoda>
                <sekundarni_metoda>Irradiance Cache</sekundarni_metoda>
                <mnozstvi_odrazu pocet_odrazu="3">Střední</mnozstvi_odrazu>
                <gammut>1</gammut>
            </globalni_iluminace>
            <ambient_occlusion>
                <barva>Černá</barva>
                <rozptyl>90</rozptyl>
                <presnost>50</presnost>
                <kontrast>0</kontrast>
                <pouzit>true</pouzit>
            </ambient_occlusion>
        </render>
    </profil>
         
    <!--profil 3-->
    <profil id="3">
        <zakladni>
            <jazyk>Angličtina</jazyk>
            <jmeno_profilu>Příroda</jmeno_profilu>
            <menu vlastnost="Soubor základních funkcí">Základní</menu>
            <tvurce pohlavi="žena" vek= "23 let">Eva Novotná</tvurce>
            <ukladani_projektu ulozeni="C:\Zbrush\nature">Složka přírody Zbrush</ukladani_projektu>
            <vytvoreni_profilu>
                <datum>2016-08-17</datum>
                <cas>22:24:35</cas>
            </vytvoreni_profilu>
        </zakladni>
        <nastaveni_modelu>
            <tvar>
                <vychozi_tvar>Rectangle</vychozi_tvar>
                <polygonalni_rozliseni polygony="3000">Střední</polygonalni_rozliseni>
                <tvar_polygonu>Čtverce</tvar_polygonu>
                <velikost_modelu>50x40x30</velikost_modelu>
                <umisteni>0,0,0</umisteni>
                <rotace>0,0,0</rotace>
            </tvar>
            <osy>
                <umisteni>20,40,50</umisteni>
                <rotace>0,0,0</rotace>
                <viditelnost>true</viditelnost>
            </osy>
            <textura>
                <barva>Zelená</barva>
                <odrazivost>10</odrazivost>
                <hrbolatost>20</hrbolatost>
                <jas>10</jas>
                <sum>30</sum>
                <alpha>35</alpha>
            </textura>
        </nastaveni_modelu>
        <scena>
            <pozadi typ=".jpg">Obloha</pozadi>
            <slunce>Přednastavené</slunce>
            <obloha>Přednastavené</obloha>
            <stin>Ostrý</stin>
            <mraky>Volumetrické</mraky>
            <podlaha>Přednastavené</podlaha>  
        </scena>
        <render>
            <rendrovaci_system>Fyzikální</rendrovaci_system>
            <vystup>
                <sirka>1280</sirka>
                <vyska>720</vyska>
                <rozliseni>72 pixelů</rozliseni>
                <soubor typ=".png">render</soubor>
            </vystup>
            <vyhlazovani>
                <vyhlazeni>Geometrie</vyhlazeni>
                <filtr>Kubický</filtr>
                <vlastni_velikost>true</vlastni_velikost>
                <mira_mip mip="50">Vysoká</mira_mip>
                <male_fragmenty>Hybridní</male_fragmenty>
            </vyhlazovani>
            <globalni_iluminace>
                <primarni_metoda>Irradiance Cache</primarni_metoda>
                <sekundarni_metoda>Irradiance Cache</sekundarni_metoda>
                <mnozstvi_odrazu pocet_odrazu="8">Vysoká</mnozstvi_odrazu>
                <gammut>1</gammut>
            </globalni_iluminace>
            <ambient_occlusion>
                <barva>Černá</barva>
                <rozptyl>90</rozptyl>
                <presnost>50</presnost>
                <kontrast>0</kontrast>
                <pouzit>true</pouzit>
            </ambient_occlusion>
        </render>
    </profil>   
         
    <!--profil 4-->
    <profil id="4">
        <zakladni>
            <jazyk>Angličtina</jazyk>
            <jmeno_profilu>Zvířata</jmeno_profilu>
            <menu vlastnost="Soubor extra funkcí">Rozšířené</menu>
            <tvurce pohlavi="žena" vek= "41 let">Marie Černá</tvurce>
            <ukladani_projektu ulozeni="C:\Zbrush\animals">Složka zvířat Zbrush</ukladani_projektu>
            <vytvoreni_profilu>
                <datum>2014-01-12</datum>
                <cas>21:25:15</cas>
            </vytvoreni_profilu>
        </zakladni>
        <nastaveni_modelu>
            <tvar>
                <vychozi_tvar>Rectangle</vychozi_tvar>
                <polygonalni_rozliseni polygony="80000">Vysoké</polygonalni_rozliseni>
                <tvar_polygonu>Trojúhelníky</tvar_polygonu>
